ifeq ($(CONFIG_OF),y)

dtb-$(CONFIG_MACH_KIRKWOOD) += \
	kirkwood-spacemonkey.dtb
endif

dtstree		:= $(srctree)/$(src)
dtb-$(CONFIG_OF_ALL_DTBS) := $(patsubst $(dtstree)/%.dts,%.dtb, $(wildcard $(dtstree)/*.dts))

always		:= $(dtb-y)
clean-files	:= *.dtb
